DROP TABLE Segment CASCADE CONSTRAINTS PURGE;
DROP TABLE Salle CASCADE CONSTRAINTS PURGE;
DROP TABLE Poste CASCADE CONSTRAINTS PURGE;
DROP TABLE Logiciel CASCADE CONSTRAINTS PURGE;
DROP TABLE Installer CASCADE CONSTRAINTS PURGE;
DROP TABLE Types CASCADE CONSTRAINTS PURGE;