DROP TABLE employe CASCADE CONSTRAINTS PURGE;
DROP TABLE chantier CASCADE CONSTRAINTS PURGE;
DROP TABLE vehicule CASCADE CONSTRAINTS PURGE;
DROP TABLE visite CASCADE CONSTRAINTS PURGE;
DROP TABLE transporter CASCADE CONSTRAINTS PURGE;